### ISSUE TITLE
Best way to define a logger in a workflow and activity class

### ISSUE THREAD

**Issue by kalpitad** [aws/aws-flow-ruby#93]
Hi there, I have a best practices question related to SWF's Flow Framework for Ruby.

In a nutshell, my project looks like this: workflows —> activities —> helper classes. I’m also using an external logging service (LogEntries) and hence need to set up logger variables for each workflow, activity, and helper class. I’m trying to figure out the smartest way to do this, based on how the processes are managed by SWF. I will be running these workers on an AWS Flow Opswork layer. For reference, my code looks something like this `@logger = Le.new(‘<app_token>', debug: true)`, where `Le` is from the LogEntries ruby gem.

My specific question: Does it make sense to define a `logger` *instance variable* in each class, or is it better to use *class variables*? Or does it not really matter?

Thanks in advance!

**Comment by pmohan6** [comment]
From Flow's perspective, I don't see any particular reason for picking one over the other.

On a side note, If you are logging something inside a workflow body, make sure that you check if replay is ongoing to avoid duplicate log messages like so -

@logger.info "foo" unless decision_context.workflow_clock.replaying

**Comment by kalpitad** [comment]
@pmohan6 - Thanks for the reply. I think that I'm confused about the `number_of_forks_per_worker` option in the AWS Flow runner specification file (also on the OpsWork AWS Flow (Ruby) App settings page). The definition on [this] (http://docs.aws.amazon.com/amazonswf/latest/awsrbflowguide/cmd-aws-flow-ruby.html) page: "The number of forked processes that are spawned per activity worker. This sets the number of activity tasks that an activity worker can work on in parallel. If not specified, a default value of 20 will be used." 

How are these forked processes spawned exactly? Are they exact copies of the original Activity Worker thread? Is the `initialize` method of the Activity Worker class called when each new fork is spawned, or do these processes just run specific Activity class methods invoked by the Workflow Worker?

Thanks also for the tip about `replaying`. I did see that many of the samples create a `is_replaying?` method, which encapsulates `decision_context.workflow_clock.replaying`, so I have done the same.

**Comment by pmohan6** [comment]
Yes, these are exact copies of the original process but they are short lived.

This is how it works -
- ActivityWorker uses [ActivityTaskPoller](https://github.com/aws/aws-flow-ruby/blob/master/aws-flow/lib/aws/decider/task_poller.rb#L107) to poll and process a task.
- When the task poller gets a task, it uses the ForkingExecutor (if forking is enabled) to [fork* a process to process the task](https://github.com/aws/aws-flow-ruby/blob/master/aws-flow/lib/aws/decider/task_poller.rb#L384).
- The forked process processes this single task, responds back to SWF and then exits. The executor ensures that the number of forked processes doesn't exceed the ```number_of_forks_per_worker```.

Does that answer your question?

* Ruby does copy on write for forked processes - so this is an exact copy till any state is changed. In older ruby versions (I think < 2.0), the mark step of GC would end up dirtying all objects, because of which copy-on-write didn't really work the way it was supposed to.

**Comment by kalpitad** [comment]
:+1: This helps a lot. Thanks so much!
